name: Build

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build

      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: git add .
      - run: git commit -am "Build"
      - run: git push