# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build for macOS

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-12

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'        
    - run: npm ci --prefix ./build/public
    - run: npm run make --prefix ./build/public
    - uses: actions/upload-artifact@v3
      with:
        name: macos-installer
        path: ./build/public/out/make/zip/darwin/x64/